# CI/CD pipeline for Ryan's Gitlab Runner to automate test running for Dev branch

stages:          # List of stages for jobs, and their order of execution
  - test

unit-test-job:
  stage: test   
  script:
    - echo "Running unit tests..."
    - go test ./candlelight-api/...
    - go test ./candlelight-ruleengine/...
    - go test ./candlelight-models/...
