# CI/CD pipeline for Ryan's Gitlab Runner to automate deployment of new backend code

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

unit-test-job:
  stage: test   
  script:
    - echo "Running unit tests..."
    - go test ./candlelight-api/...
    - go test ./candlelight-ruleengine/...
    - go test ./candlelight-models/...

build-job:       # This job runs in the build stage, and only runs if the test job completes successfully
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "Building and pushing new docker image..."
    - docker login -u candlelightdevteam -p dckr_pat_Vag7IPMiBX8qg23Z98Mu45jiS3M
    - docker build --no-cache -t candlelightdevteam/candlelight-backend:latest .
    - docker push candlelightdevteam/candlelight-backend:latest
  
deploy-job:      #SSH into EC2 instance and run the backend-rebuild script, which will stop server, remove old container/image, pull updated image, and rerun the server. This wips the DB since we don't have a volume set up
  stage: deploy  
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment: production
  script:
    - echo "Executing redeploy script on remote EC2 instance..."
    - ssh ec2-3-19-232-179.us-east-2.compute.amazonaws.com -i ~/.ssh/candlelight-dev-login.pem -l ec2-user 'sudo bash ./candlelight/candlelight-backend/rebuildbackend.sh'

