services:  
  web:
    volumes:
      - ./logs/:/logs/:delegated
    build: .
    ports:
      - "10000:10000"
    environment:
      REDIS_ADDRESS: "redis:6379"
    image: candlelight-backend:latest
  redis:
    image: "redis:alpine"
