services:  
  web:
    build: .
    ports:
      - "80:80"
    environment:
      REDIS_ADDRESS: "redis:6379"
    image: capstone-cs.eng.utah.edu:5050/candlelight/candlelight-backend:latest
  redis:
    image: "redis:alpine"